server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backendprojectdb
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #create #update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  profiles:
    include:
      - open   #application-open.yml
      - oauth2 #application-oauth2.yml

  # JSON 직렬화 설정
  jackson:
    serialization:
      fail-on-empty-beans: false

  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: localhost #Docker 내부 배포 시 환경변수로 'rabbitmq'주입 가능
    port: 5672
    username: admin #docker run 의 default user
    password: 1234 #docker run 의 default password

rabbitmq.queue.name: ec2.queue
rabbitmq.exchange.name: ec2.exchange
rabbitmq.question.routing.key: ec2.routing.#

#로그 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

img.path.item: file:///E:/fitmate/backend/item/
img.path.community: file:///E:/fitmate/backend/community/
